<a href="https://colab.research.google.com/github/22Ifeoma22/22Ifeoma22/blob/main/03_EagerExecution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
tf.executing_eagerly()

True

In [ ]:
x = [[10.]]

res = tf.matmul(x, x)

res

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[100.]], dtype=float32)>

In [ ]:
a = tf.constant([[10, 20],
                 [30, 40]])

a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [ ]:
b = tf.add(a, 2)

print(b)

tf.Tensor(
[[12 22]
 [32 42]], shape=(2, 2), dtype=int32)


In [ ]:
print(a * b)

tf.Tensor(
[[200 231]
 [264 299]], shape=(2, 2), dtype=int32)


In [ ]:
m = tf.Variable([4.0, 5.0, 6.0], tf.float32, name='m')

c = tf.Variable([1.0, 1.0, 1.0], tf.float32, name='c')

In [ ]:
m

<tf.Variable 'm:0' shape=(3,) dtype=float32, numpy=array([4., 5., 6.], dtype=float32)>

In [ ]:
c

<tf.Variable 'c:0' shape=(3,) dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [ ]:
x = tf.Variable([100.0, 100.0, 100.0], tf.float32, name='x')

x

<tf.Variable 'v:0' shape=(3,) dtype=float32, numpy=array([100., 100., 100.], dtype=float32)>

In [ ]:
y = m * x + c

y

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([401., 501., 601.], dtype=float32)>

### Dynamic Control Flow

In [ ]:
def tensorflow(max_num):

    counter = tf.constant(0)
    max_num = tf.constant(max_num)

    for num in range(0, max_num.numpy() + 1):
        num = tf.constant(num)

        if int(num % 3) == 0 and int(num % 5) == 0:
            print('Divisible by 3 and 5: ', num.numpy())

        elif int(num % 3) == 0:
            print('Divisible by 3: ', num.numpy())

        elif int(num % 5) == 0:
            print('Divisible by 5: ', num.numpy())

        else:
            print(num.numpy())

        counter += 1

In [ ]:
tensorflow(15)

Divisible by 3 and 5:  0
1
2
Divisible by 3:  3
4
Divisible by 5:  5
Divisible by 3:  6
7
8
Divisible by 3:  9
Divisible by 5:  10
11
Divisible by 3:  12
13
14
Divisible by 3 and 5:  15
