<a href="https://colab.research.google.com/github/22Ifeoma22/22Ifeoma22/blob/main/PytorchTensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Run following command to install pytorch<br>
conda install pytorch torchvision -c pytorch -y

In [12]:
import torch

print(torch.__version__)

2.3.0+cu121


#### Creating Tensors

#### A Tensor initialized with a specific array

In [13]:
tensor_array = torch.Tensor([[1,2],[4,5]])
tensor_array

tensor([[1., 2.],
        [4., 5.]])

#### An un-initialized Tensor of shape 3X3 allocated space in memory

In [14]:
tensor_uninitialized = torch.Tensor(3, 3)

#### numel() returns the number of elements in a tensor

In [15]:
torch.numel(tensor_uninitialized)

9

Creating Tensor without initialization sometimes lead to "RuntimeError: Overflow when unpacking long" error.<br>
Because torch.empty gives uninitialized memory, so we may or may not get a large value from it.

In [16]:
tensor_uninitialized

tensor([[1.0838e-08, 4.3208e-05, 4.3681e-05],
        [1.2961e+16, 2.1707e-18, 7.0952e+22],
        [1.7748e+28, 1.8176e+31, 7.2708e+31]])

#### A tensor of size 2x3 initialized with random values

In [17]:
tensor_initialized = torch.rand(2, 3)
tensor_initialized

tensor([[0.8873, 0.3770, 0.6854],
        [0.6424, 0.4936, 0.4440]])

#### Tensors can be set to have specific data types
Here we create one poplulated with random integers

In [18]:
tensor_int = torch.randn(5, 3).type(torch.IntTensor)
tensor_int

tensor([[ 0,  0,  0],
        [-1,  0,  0],
        [ 0,  0,  0],
        [ 0,  0, -1],
        [ 0,  0,  0]], dtype=torch.int32)

#### A Tensor of type Long

In [19]:
tensor_long = torch.LongTensor([1.0, 2.0, 3.0])
tensor_long

tensor([1, 2, 3])

#### A tensor of type Byte
This holds unsigned int values from 0 to 255. Values outside of that range are expressed relative to 256

Hypothesis
The error message "RuntimeError: value cannot be converted to type uint8 without overflow" indicates that you are trying to create a torch.ByteTensor with values that are outside the valid range for the unsigned 8-bit integer data type. torch.ByteTensor expects values between 0 and 255 (inclusive). The value 261 in your input list exceeds this limit, causing the overflow.

In [22]:
tensor_byte = torch.ByteTensor([0, 255, 1, 0]) # Replace 261 and -5 with valid values between 0 and 255
print(tensor_byte)

tensor([  0, 255,   1,   0], dtype=torch.uint8)


#### A tensor of size 10 containing all ones

In [24]:
tensor_ones = torch.ones(10)
tensor_ones

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### A tensor of size 10 containing all zeros

In [25]:
tensor_zeroes = torch.zeros(10)
tensor_zeroes

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an identity 3x3 tensor

In [26]:
tensor_eye = torch.eye(3)
tensor_eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

#### Get the list of indices of non-zero elements in a tensor
[ i, j ] index for non-zero elements

In [27]:
non_zero = torch.nonzero(tensor_eye)
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2]])

#### Use ones_like() with an existing tensor to create a tensor of ones with the same shape as that tensor
A tensor with same shape as eye. Fill it with 1.

In [28]:
tensor_ones_shape_eye = torch.ones_like(tensor_eye)
tensor_ones_shape_eye

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## Inplace / Out-of-place
The first difference is that ALL operations on the tensor that operate in-place on it will have an "\_" postfix. For example, add is the out-of-place version, and add\_ is the in-place version.

#### .fill_ is in-place operation and it doesnt have any out-place equivalent

In [31]:
initial_tensor = torch.rand(3, 3)

initial_tensor.fill_(3)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

#### The add() method does an out-of-place add operation and returns a new tensor
This is assigned to the new_tensor variable

In [33]:
new_tensor = initial_tensor.add(4)
new_tensor

tensor([[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]])

#### The original tensor is unchanged

In [34]:
initial_tensor

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

#### The add\_ method does an in-place add, changing the calling tensor

In [35]:
initial_tensor.add_(5)
initial_tensor

tensor([[8., 8., 8.],
        [8., 8., 8.],
        [8., 8., 8.]])

#### The new_tensor was a separate copy and is unaffected

In [36]:
new_tensor

tensor([[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]])

## Interoperablity between Numpy arrays and Pytorch Tensors

In [37]:
import numpy as np

#### Converting a numpy array to a Tensor

In [38]:
numpy_arr = np.array([1, 2, 3])
numpy_arr

array([1, 2, 3])

In [39]:
tensor = torch.from_numpy(numpy_arr)
tensor

tensor([1, 2, 3])

#### Converting tensor to numpy arrays

In [40]:
numpy_from_tensor = tensor.numpy()
numpy_from_tensor

array([1, 2, 3])

#### The Numpy arrays and Tensor share the same memory
The tensor and numpy_from_tensor are shallow copies and share the same memory as the original numpy array. Modifying the original array affects the values of both tensor and numpy_from_tensor

In [41]:
numpy_arr[1] = 4
numpy_arr

array([1, 4, 3])

In [42]:
tensor

tensor([1, 4, 3])

In [43]:
numpy_from_tensor

array([1, 4, 3])

#### Indexing

In [44]:
initial_tensor = torch.rand(2, 3)
initial_tensor

tensor([[0.2135, 0.6295, 0.6911],
        [0.1712, 0.0298, 0.0689]])

#### Selecting individual elements from the tensor
Select the 1st row, 3rd column

In [45]:
initial_tensor[0, 2]

tensor(0.6911)

#### Slicing
Select all rows, and the elements from the 2nd column onwards

In [46]:
initial_tensor[:,1:]

tensor([[0.6295, 0.6911],
        [0.0298, 0.0689]])

#### Resizing

.size() method is used to check shape of the tensor

In [47]:
initial_tensor.size()

torch.Size([2, 3])

#### .shape returns the shape attribute of the tensor

In [48]:
initial_tensor.shape

torch.Size([2, 3])

#### The view() methoed
This creates a view of the calling tensor in the shape specified in the arguments. Here, we create a 1-D tensor of shape (6,) from our 2D initial_tensor

In [49]:
resized_tensor = initial_tensor.view(6)
resized_tensor.shape

torch.Size([6])

In [50]:
resized_tensor

tensor([0.2135, 0.6295, 0.6911, 0.1712, 0.0298, 0.0689])

#### view() does not create a deep copy - just a view as the name suggests
Modifying the original tensor affects the resized_tensor as they both point to the same space in memory

In [51]:
initial_tensor[0, 2] = 0.1111
resized_tensor

tensor([0.2135, 0.6295, 0.1111, 0.1712, 0.0298, 0.0689])

#### Convert 2x3 tensor to a 3x2 tensor

In [52]:
resized_tensor = initial_tensor.view(3, 2)
resized_tensor.shape

torch.Size([3, 2])

In [53]:
resized_tensor

tensor([[0.2135, 0.6295],
        [0.1111, 0.1712],
        [0.0298, 0.0689]])

#### Use of -1 as a view argument
In a situation where you would like one of the dimensions of the tensor to be inferred, the argument for that can be stated as -1. It's actual dimension will be set based on the value of the other dimension.

This also applies to multi-dimensional tensors though we only use 2D tensors here

In [54]:
resized_matrix = initial_tensor.view(-1, 2)
resized_matrix.shape

torch.Size([3, 2])

#### The reshaping must contain valid arguments
The view method must have arguments which are factors of the number of elements in the tensor. Specifying values which are not factors will result in an error

In [62]:
resized_matrix = initial_tensor.view(-1, 3)

## Sorting tensors
Tensors can be sorted along a specified dimension. If no dimension is specified, the last dimension is picked by default

In [63]:
initial_tensor

tensor([[0.2135, 0.6295, 0.1111],
        [0.1712, 0.0298, 0.0689]])

#### torch.sort() returns two tensors
* one original sorted tensor
* one with index of elements in sorted order

The rows in this tensor will be sorted as they represent the last dimension

In [64]:
sorted_tensor, sorted_indices = torch.sort(initial_tensor)

In [65]:
sorted_tensor

tensor([[0.1111, 0.2135, 0.6295],
        [0.0298, 0.0689, 0.1712]])

In [66]:
sorted_indices

tensor([[2, 0, 1],
        [1, 2, 0]])

#### Specifying a dimension to sort on
Here, the tensor is sorted on its columns

In [67]:
sorted_tensor, sorted_indices = torch.sort(initial_tensor, dim=0)
sorted_tensor

tensor([[0.1712, 0.0298, 0.0689],
        [0.2135, 0.6295, 0.1111]])

In [68]:
sorted_indices

tensor([[1, 1, 1],
        [0, 0, 0]])

#### torch.topk() returns two tensors
* one with max k elements in the specific dimension (k being the second argument)
one with index of elements having max element

In [69]:
topk_tensor, topk_indices = torch.topk(initial_tensor, 2)
topk_tensor

tensor([[0.6295, 0.2135],
        [0.1712, 0.0689]])

In [70]:
topk_indices

tensor([[1, 0],
        [0, 2]])

## Math Operations
Pytorch supports a number of mathematical operations which can be performed on tensors. We take a look at a few of them here

#### Float tensors

In [71]:
tensor_float= torch.FloatTensor([-1.1, -2.2, 3.3])
tensor_float

tensor([-1.1000, -2.2000,  3.3000])

#### Absolute values

In [72]:
tensor_abs = torch.abs(tensor_float)
tensor_abs

tensor([1.1000, 2.2000, 3.3000])

#### Addition
Addition of single value tensors

In [73]:
float1 = torch.FloatTensor([2])
float2 = torch.FloatTensor([3])
float1 + float2

tensor([5.])

#### Adding array-like tensors
Two tensors of the same shape can be added by summing up the values of elements at the same index locations

In [74]:
rand1 = torch.abs(torch.randn(2, 3))
rand2 = torch.abs(torch.randn(2, 3))

print(rand1, '\n', rand2)

tensor([[2.0650, 0.2788, 0.1667],
        [0.5195, 1.8929, 0.1567]]) 
 tensor([[0.0769, 0.6372, 0.0696],
        [0.7901, 1.9966, 0.2203]])


#### Addition using the + operator

In [75]:
add1 = rand1 + rand2
add1

tensor([[2.1419, 0.9160, 0.2362],
        [1.3096, 3.8895, 0.3770]])

#### Addition using the add() function

In [76]:
add2 = torch.add(rand1, rand2)
add2

tensor([[2.1419, 0.9160, 0.2362],
        [1.3096, 3.8895, 0.3770]])

#### In-place addition using add_()

In [77]:
rand1.add_(rand2)
rand1

tensor([[2.1419, 0.9160, 0.2362],
        [1.3096, 3.8895, 0.3770]])

#### Adding a scalar value to all tensor elements
Using the plus sign

In [78]:
add_scalar_plus = rand1 + 10
add_scalar_plus

tensor([[12.1419, 10.9160, 10.2362],
        [11.3096, 13.8895, 10.3770]])

Using the add() function

In [79]:
add_scalar = torch.add(rand1, 10)
add_scalar

tensor([[12.1419, 10.9160, 10.2362],
        [11.3096, 13.8895, 10.3770]])

In [80]:
tensor = torch.Tensor([[-1, 0.3, 2],
                      [-4, 5, -0.4]
                     ])

#### Element-wise division
The div() and mul() functions can be used to divide and multiply the values in a tensor. Here, we do an element-wise division between two tensors

In [81]:
tensor_div = torch.div(tensor, tensor + 0.3)
tensor_div

tensor([[1.4286, 0.5000, 0.8696],
        [1.0811, 0.9434, 4.0000]])

#### Element-wise multiplicaton

In [82]:
tensor_mul = torch.mul(tensor, tensor)
tensor_mul

tensor([[ 1.0000,  0.0900,  4.0000],
        [16.0000, 25.0000,  0.1600]])

#### Multiplying with a scalar
Both mul() and div() can be used with a scalar to perform a div() or mul() of all elements with a scalar quantity

In [83]:
tensor_mul = torch.mul(tensor, 10)
tensor_mul

tensor([[-10.,   3.,  20.],
        [-40.,  50.,  -4.]])

#### Clamp the value of a Tensor
There will be occasions where you would like to set upper and lower limits for the values in a tensor. This is where the clamp function is used. The value of an element is set to:
* min if if x<sub>i</sub> < min
* x<sub>i</sub> if min < x<sub>i</sub> < max
* max if x<sub>i</sub> > max

In [84]:
tensor_clamp = torch.clamp(tensor, min=-0.5, max=0.5)
tensor_clamp

tensor([[-0.5000,  0.3000,  0.5000],
        [-0.5000,  0.5000, -0.4000]])

#### Transpose with t()

In [ ]:
transposed_tensor = tensor.t()
transposed_tensor

## Vector Multiplication

#### Dot product

In [85]:
t1 = torch.Tensor([4, 2])
t2 = torch.Tensor([3, 1])

In [86]:
dot_product = torch.dot(t1, t2)
dot_product

tensor(14.)

#### Matrix Vector product
If mat is a (n×m) tensor, vec is a 1-D tensor of size m, out will be 1-D of size n.

In [87]:
matrix = torch.Tensor([[2, 5, 3],
                   [4, 1, 0]
                  ])

vector = torch.Tensor([3, 5, 0])

In [88]:
matrix_vector = torch.mv(matrix, vector)
matrix_vector

tensor([31., 17.])

#### Matrix multiplication

In [89]:
another_matrix = torch.Tensor([[1, 3],
                               [2, 0],
                               [0, 5]
                              ])

In [90]:
matrix_mul = torch.mm(matrix, another_matrix)
matrix_mul

tensor([[12., 21.],
        [ 6., 12.]])